---
kind: pipeline
type: docker
name: android

concurrency:
  limit: 1

steps:
- name: build
  image: mingc/android-build-box:1.22.0
#  when:
#    branch:
#    - master
  commands:
#  - . $HOME/.bash_profile   # Enable jenv
  - echo "pwd $HOME"
  - pwd $HOME
  - echo "ls $HOME"
  - ls $HOME
  - jenv local 11           # Set current Java env to 11
  - ./gradlew build

#- name: Signed .apk
#  image: mingc/android-build-box:1.21.1
#  when:
#    branch:
#    - master
#  environment:
#    KEY_LOCATION:
#      from_secret: key-location
#    STORE_PASSWORD:
#      from_secret: mateusz-bak.key-store-password
#    KEY_ALIAS:
#      from_secret: mateusz-bak.key-alias
#    KEY_PASSWORD:
#      from_secret: mateusz-bak.key-password
#  commands:
#  - wget -q $KEY_LOCATION
#  - cp mateusz-bak.jks app/mateusz-bak.jks
#  - ./gradlew assembleRelease -Pandroid.injected.signing.store.file=mateusz-bak.jks -Pandroid.injected.signing.store.password=$STORE_PASSWORD -Pandroid.injected.signing.key.alias=$KEY_ALIAS -Pandroid.injected.signing.key.password=$KEY_PASSWORD
#  - ls -l app/build/outputs/apk/release

  steps:
- name: notify
  image: plugins/matrix
  settings:
    homeserver: https://matrix.org
    roomid:
      from_secret: matrix_roomid
    username:
      from_secret: matrix_username
    password:
      from_secret: matrix_password
    template: >
      Build for {{repo.name}} on branch {{build.branch}}, commit: {{truncate build.commit 8}} triggered by {{build.author}} finished.
...
