name: Format Dart code

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  dart:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.2'
    - run: dart format --set-exit-if-changed lib
