name: Test build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  android_apk_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ vars.FLUTTER_VERSION }}
    - name: Configure Keystore for Android
      run: |
        echo "$PLAY_STORE_UPLOAD_KEY" | base64 --decode > app/upload-keystore.jks
        echo "storeFile=upload-keystore.jks" >> key.properties
        echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> key.properties
        echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> key.properties
        echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> key.properties
      env:
        PLAY_STORE_UPLOAD_KEY: ${{ vars.PLAY_STORE_UPLOAD_KEY_TEST }}
        KEYSTORE_KEY_ALIAS: ${{ vars.KEYSTORE_KEY_ALIAS_TEST }}
        KEYSTORE_KEY_PASSWORD: ${{ vars.KEYSTORE_KEY_PASSWORD_TEST }}
        KEYSTORE_STORE_PASSWORD: ${{ vars.KEYSTORE_STORE_PASSWORD_TEST }}
      working-directory: android
    - run: flutter config --no-analytics
    - run: flutter pub get
    - run: flutter build -v apk

  android_appbundle_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ vars.FLUTTER_VERSION }}
    - name: Configure Keystore for Android
      run: |
        echo "$PLAY_STORE_UPLOAD_KEY" | base64 --decode > app/upload-keystore.jks
        echo "storeFile=upload-keystore.jks" >> key.properties
        echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> key.properties
        echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> key.properties
        echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> key.properties
      env:
        PLAY_STORE_UPLOAD_KEY: ${{ vars.PLAY_STORE_UPLOAD_KEY_TEST }}
        KEYSTORE_KEY_ALIAS: ${{ vars.KEYSTORE_KEY_ALIAS_TEST }}
        KEYSTORE_KEY_PASSWORD: ${{ vars.KEYSTORE_KEY_PASSWORD_TEST }}
        KEYSTORE_STORE_PASSWORD: ${{ vars.KEYSTORE_STORE_PASSWORD_TEST }}
      working-directory: android
    - run: flutter config --no-analytics
    - run: flutter pub get
    - run: flutter build -v appbundle

  ios_build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ vars.FLUTTER_VERSION }}
    - run: flutter config --no-analytics
    - run: flutter pub get
    - run: flutter build ios --no-codesign
