name: Test build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  android_apk_build_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.7'
    - run: rm /home/runner/work/openreads-android/openreads-android/lib/l10n/app_kaa.arb
    - run: flutter pub get
    - run: flutter build apk

  android_appbundle_build_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.7'
    - run: rm /home/runner/work/openreads-android/openreads-android/lib/l10n/app_kaa.arb
    - run: flutter pub get
    - run: flutter build appbundle

  android_apk_build_macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.7'
    - run: rm /home/runner/work/openreads-android/openreads-android/lib/l10n/app_kaa.arb
    - run: flutter pub get
    - run: flutter build apk

  android_appbundle_build_macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.7'
    - run: rm /home/runner/work/openreads-android/openreads-android/lib/l10n/app_kaa.arb
    - run: flutter pub get
    - run: flutter build appbundle
