name: Test build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  android_apk_build:
    name: Test build of Android apk
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ vars.FLUTTER_VERSION }}
    - name: Remove signing config
      run: awk '/release \{/ {f=1} !f; /}/ && f {f=0}' build.gradle > temp && mv temp build.gradle
      working-directory: android/app
    - run: flutter config --no-analytics
    - run: flutter pub get
    - run: flutter build -v apk

  android_appbundle_build:
    name: Test build of Android appbundle
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ vars.FLUTTER_VERSION }}
    - name: Remove signing config
      run: awk '/release \{/ {f=1} !f; /}/ && f {f=0}' build.gradle > temp && mv temp build.gradle
      working-directory: android/app
    - run: flutter config --no-analytics
    - run: flutter pub get
    - run: flutter build -v appbundle

  ios_build:
    name: Test build of iOS ipa
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ vars.FLUTTER_VERSION }}
    - run: flutter config --no-analytics
    - run: flutter pub get
    - run: flutter build ios --no-codesign
